<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.nanometer</groupId>
        <artifactId>nanometer-parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>nanometer-example</artifactId>
    <packaging>jar</packaging>

    <name>Nanometer :: Example Project</name>
    <description>Example E-Commerce Application Demonstrating Embedded Nanometer APM</description>

    <dependencies>
        <dependency>
            <groupId>io.nanometer</groupId>
            <artifactId>nanometer-api</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>se.deversity.async-test-lib</groupId>
            <artifactId>async-test-lib</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
